config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:show] do
    member do
      get :exact_match
      post :toggle_product
    end
  end
  resources :exact_requests, only: [:show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "videos#index"
  resources :videos
  post "/click_product" => "videos#click_product"

  post '/track_scroll' => "videos#track_scroll"
  post '/register_category_click' => "videos#register_category_click"
  post '/record_session_duration' => "videos#record_session_duration"
  post '/update_session_time' => "videos#update_session_time"
  post '/track_toast_click' => "videos#track_toast_click"
  post '/active_media_duration' => "videos#active_media_duration"
  get 'videosm/:id' => "videos#show_manual", as: "show_manual"
  get 'videos/woc/:id' => "videos#woc", as: "woc"
  get '/analytics/:id' => "videos#analytics"
  post 'videos/dynamic_show' => 'videos#dynamic_show'
  get 'videos/rv/:id' => "videos#rv", as: "rv"

  # FOR LINEAR LANDING
  resources :scenes
  get '/t&c' => "scenes#t_and_c", as: "t_and_c"
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :episode, touch: true
  has_many :scene_products
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  def index
    if !session[:linear_landing]
      session[:linear_landing] = SecureRandom.uuid
      gon.event_tracker = {category: "Session", action: "Landed", label: ""}
    end
    @scenes = Scene.where(episode_id: 2)
    @products = []
    if (params[:filter])
      case params[:type]
        when "products"
          @products = SceneProduct.joins(scene: :episode).where(episodes: {id: params[:episode]})
          @products = @products.to_a.uniq {|x| [x.title]}
        when "scenes"
          @scenes = Scene.where(episode_id: params[:episode])
        when "characters"
          @products = SceneProduct.where(seen_on: params[:character])
        else
          puts "Nothing"
      end
    end
  end

  def show
    @scene = Scene.find(params[:id])
    if params[:type] == 'products'
      gon.event_tracker = {category: "MenuClick", action: "Click", label: "Product"}
    else 
      gon.event_tracker = {category: "MenuClick", action: "Click", label: "Scene"}
    end
    @products = @scene.scene_products
    @products = @products.sort_by &:product_annot
  end

  def t_and_c
  end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_modalNeelofa.html.erb
<!-- Modal -->
<div class="modal fade" id="modalNeelofa" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modalNeelofa" role="document">
    <div class="modal-content text-center">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title">Dapatkan gaya Helena dengan Bloom by Naelofar Hijab!</h5>
      </div>
      <div class="modal-body">

        <div class="scene-product-big-wrapper">
        <div class="scene-product-wrapper">
          <div class="scene-product-thumbnail-wrapper">
            <div class="scene-product-thumbnail" style="background-image: url(http://image.goshop.com.my/resources/ms/image/contents/prd/24/19/20042419_06_400.jpg)">
            </div>
            
          </div>
          <div class="scene-product-details">
            <p class="product-title">Bloom By Naelofar Hijab (3pcs set)</p>
            <div>
              <span class="slashed_price">RM199.00</span>
              <span class="price">RM179.10</span>
            </div>
            <p>Gunakan code <span class="discount_code">RIAFINDIT</span> untuk dapatkan discount eksklusif!</p>
            <%= link_to "Buy Now", "http://www.goshop.com.my/prd/20042419.html?utm_medium=referral&utm_source=astro_findit&utm_campaign=ria_findit_20171110&utm_content=special_bloom", class: 'btn buy_now_button', target: '_blank' %>
          </div>

        </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/scenes/_modalPromo.html.erb
<!-- Modal -->
<div class="modal fade" id="modalPromo" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modalPromo" role="document">
    <div class="modal-content text-center">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>

app/views/scenes/_product.html.erb
<% cache product do %>

  <div class="scene-product-big-wrapper" data-product-wrapper=<%= product.id %>>
    
    <div class="scene-product-wrapper">
      <div class="scene-product-thumbnail-wrapper">
        <div class="scene-product-thumbnail" style="background-image: url(<%= product.picture_url %>)">
          <span class="anno-number"><%= product.product_annot %></span>
          
        </div>
        
      </div>
      <div class="scene-product-details">
        <p class="product-title"><%= product.title %></p>
        <div>
          <% if product.slashed_price %>
            <span class="slashed_price"><%= "#{product.price}  " %></span>
          <% end %>
          <span class="price"><%= product.slashed_price %></span>
        </div>
        <p>Gunakan code <span class="discount_code">RIAFINDIT</span> untuk dapatkan discount eksklusif!</p>
        <%= link_to "Buy Now", product.product_link, class: 'btn buy_now_button', target: '_blank' %>
      </div>

    </div>

    <div class="more-details" data-more-details-row=<%= product.id %>>
      <% if product.free_gift %>
        <div class="more-details-div-0">
            <p class="scene-product-detail">Free Gifts: 

              <% product.free_gift.split(/\n/).each do |x| %>
                <p><%= "\u2022 #{x}" %></p>
              <% end %>
            </p>  
        </div> 
      <% end %>

      <div class="more-details-nested">
        <div class="more-details-div-1">
          <% if product.colors %>
          <p class="scene-product-detail">Colors: <p><%= product.colors %></p></p>
          <% end %>
          <% if product.sizes %>
            <p class="scene-product-detail">Sizes: <p><%= product.sizes %></p></p>
          <% end %>
        </div>
        <% if product.features %>
          <div class="more-details-div-2 ">
            <p class="scene-product-detail">Features: 

              <% product.features.split(/\n/).each do |x| %>
                <p><%= "\u2022 #{x}" %></p>
              <% end %>
            </p>    
          </div>
        <% end %>
        
      </div>


    </div>

  </div>

<% end %>

app/views/scenes/_scene.html.erb
<% cache scene do %>

  <div class="scene-wrapper">
  <%= link_to scene_path(id: scene.id, type: "scenes") do %>
    <div class="scene-block">
      <div class="scene-thumbnail" style="background-image: url(<%= scene.scene_url %>)">
      </div>
      <div class="scene-title">
        <%= scene.episode.name %>
      </div>
    </div>
  <% end %>
  </div>

<% end %>

app/views/scenes/_sceneProduct.html.erb
<% cache sceneProduct do %>

  <div class="scene-wrapper">
    <%= link_to scene_path(id: sceneProduct.scene_id, type: "products") do %>
      <div class="scene-block sceneProduct-block">
        <div class="sceneProduct-thumbnail" style="background-image: url(<%= sceneProduct.picture_url %>)">
        </div>
        <div class="sceneProduct-desc">
          <%= sceneProduct.title %>
          <div>
            <% if sceneProduct.slashed_price %>
              <span class="slashed_price"><%= "#{sceneProduct.slashed_price}  " %></span>
            <% end %>
            <span class="price"><%= sceneProduct.price %></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% end %>

app/views/scenes/index.html.erb
<%= render "layouts/navbar", link: "/", digital: false %>

<div id="scene-list">
  <% if @products.empty? %>
    <%= render partial: 'scene', collection: @scenes, cached: true %>
  <% else %>
    <%= render partial: 'sceneProduct', collection: @products, cached: true %>
  <% end %>
</div>

<div data-toggle="modal" data-target="#modalNeelofa" id="tap-follower">
  
</div>

<%= render "modalPromo" %>
<%= render "modalNeelofa" %>

<footer>
  <%= link_to("https://www.facebook.com/Find-It-111053949615332/") do %>
    <%= image_tag "fblogo.png" %>
  <% end %>
</footer>

app/views/scenes/show.html.erb
<%= render "layouts/navbar", link: "/", digital: false %>

<div id="scene-container">
  <div class="scene-display" style="background-image: url(<%= @scene.description %>)"></div>
  <div class="scene-products-list">
    <%= render partial: 'product', collection: @products, cached: true %>
  </div>
</div>

app/views/scenes/t_and_c.html.erb
<%= render "layouts/navbar", link: "/", digital: false %>

<div class="container" style="color: white;">
  <h2 style="color: yellow;">Promo Terms and Conditions</h2>
  <p>1. The unique code RIAFINDIT is only valid from 11 November 2017 to 17 November 2017 (“Promotion Period”) and is applicable to all new and existing customers of Go Shop (“Customer(s)”).
  </p>
  
  <p>2. Customers who purchased from Go Shop via online at www.goshop.com.my or via mobile application at m.goshop.com.my during the Promotion Period is entitled to an instant promo code “RIAFINDIT” (“Promo Code”) for 10% discount off the selling price of the selected products served on www.astrofindit.com.
  </p>

  <p>3. Customers must register the Promo Code first before applying it at the check-out page prior to payment and follow instructions given therein.
  </p>

  <p>4. Each user can generate multiple “RIAFINDIT” promo codes and apply them on more than one product in their checkout basket so long as those products are part of the selected range served on www.astrofindit.com
  </p>

  <p>5. The Promo Code is valid for use from 11 November 2017 to 17 November 2017 only (“Redemption Period”). Any use or redemption of the Promo Code made before or after the Redemption Period will be invalid and rejected. 
  </p>

  <p>6. Promo code "RIAFINDIT" cannot be used in conjunction with other Go Shop discount codes that may be used in place of the RIAFINDIT discount code.  
  </p>

  <p>7. The use of the Promo Code is applicable for non-cash purchases (credit card, debit card, Easy Payment Scheme and bank transfer) and cash on delivery (COD) purchases.
  </p>

  <p>8. The terms herein on the use of the Promo Code shall also be read with the terms and conditions on Go Shop’s General Terms and Conditions on Promo Codes which can be found on www.goshop.com.my 
  </p>
</div>