config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:show] do
    member do
      get :exact_match
      post :toggle_product
    end
  end
  resources :exact_requests, only: [:show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "videos#index"
  resources :videos
  post "/click_product" => "videos#click_product"

  post '/track_scroll' => "videos#track_scroll"
  post '/register_category_click' => "videos#register_category_click"
  post '/record_session_duration' => "videos#record_session_duration"
  post '/update_session_time' => "videos#update_session_time"
  post '/track_toast_click' => "videos#track_toast_click"
  post '/active_media_duration' => "videos#active_media_duration"
  get 'videosm/:id' => "videos#show_manual", as: "show_manual"
  get 'videos/woc/:id' => "videos#woc", as: "woc"
  get '/analytics/:id' => "videos#analytics"
  post 'videos/dynamic_show' => 'videos#dynamic_show'
  get 'videos/rv/:id' => "videos#rv", as: "rv"

  # FOR LINEAR LANDING
  resources :scenes
  get '/t&c' => "scenes#t_and_c", as: "t_and_c"
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :products
  has_many :views
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_categories, only: [:index, :show]

  def index
    @videos = if params[:category]
      Video.where(content_category: params[:category])
    else
      Video.all
    end

    @videos = @videos.page(params[:page]).per(12)
  end

  def show
    @video = Video.find(params[:id])
    @productss = @video.products.order(:id)

    if params[:id] == "1"
      @products = @productss.reject {|x| (x.match_type == 'Similar' && @productss[x.id - 2].match_type == 'Exact') }
    else
      @products = @productss
    end

    if !session[:user]
      @view = View.create(video_id: @video.id, view_type: "wc")
      session[:user] = @view.id
      session[:time] = DateTime.now
    else
      @view = View.find(session[:user])
    end
    @all_other_video = Video.where.not(id: [params[:id]]).shuffle
    @product_categories = @products.pluck(:product_category).uniq
    if params[:j]
      current_count = @view.jumps
      @view.update(jumps: current_count + 1)
    end
  end

  def click_product
    if params[:view_id]
      Click.create(view_id: params[:view_id], product_id: params[:product_id])
    end
    @product = Product.find(params[:product_id])
    render json: "Success"
  end

  def track_scroll
    if params[:view_id] && params[:view_id] != ""
      @view = View.find(params[:view_id])
      @view.update(scrolled: true)
    end
    render json: "Success"
  end

  def track_toast_click
    if params[:view_id] && params[:view_id] != ""
      @view = View.find(params[:view_id])
      @view.update(more_info: true)
    end
    render json: "Success"
    # redirect_to @url
  end

  def show_manual
    @video = Video.find(params[:id])
    @products = @video.products
    @all_other_video = Video.where.not(id: [params[:id]]).shuffle
    @product_categories = @products.pluck(:product_category).uniq
  end

  def woc
    @video = Video.find(params[:id])
    # @products = @video.products
    if !session[:user]
      @view = View.create(video_id: @video.id, view_type: "woc")
      session[:user] = @view.id
      session[:time] = DateTime.now
    else
      @view = View.find(session[:user])
    end
    @all_other_video = Video.where.not(id: [params[:id]]).shuffle
    # @product_categories = @products.pluck(:product_category).uniq
    if params[:j]
      current_count = @view.jumps
      @view.update(jumps: current_count + 1)
    end
  end

  def analytics
    @id = params[:id]
    if @id == "0"
      @total_views = View.all
      @scrolled_views = View.where(scrolled: true).pluck(:id)
      @more_info_views = View.where(more_info: true).pluck(:id)
      @counter_array = []
      @total_views.each do |x|
        if x.category_clicks != []
          @counter_array << x.id
        end
      end
      @overall_views_clicks = Click.all.pluck(:view_id)
      @original_total = @scrolled_views | @more_info_views | @overall_views_clicks
      @current_total = @scrolled_views | @more_info_views | @overall_views_clicks | @counter_array
      @scrolled_and_more_info = @scrolled_views & @more_info_views
      @scrolled_and_clicks = @scrolled_views & @overall_views_clicks
      @more_info_and_clicks = @more_info_views & @overall_views_clicks
      @scrolled_and_cat_clicks = @scrolled_views & @counter_array
      @all = @overall_views_clicks & @scrolled_views & @more_info_views & counter_array
    else
      @total_views = View.where(video_id: @id)
      @scrolled_views = View.where(scrolled: true, video_id: @id).pluck(:id)
      @more_info_views = View.where(more_info: true, video_id: @id).pluck(:id)
      @counter_array = []
      @total_views.each do |x|
        if x.category_clicks != []
          @counter_array << x.id
        end
      end
      @overall_views_clicks = Click.joins(view: :video).where(videos: {id: @id}).pluck(:view_id)
      @original_total = @scrolled_views | @more_info_views | @overall_views_clicks
      @current_total = @scrolled_views | @more_info_views | @overall_views_clicks | @counter_array
      @scrolled_and_more_info = @scrolled_views & @more_info_views
      @scrolled_and_clicks = @scrolled_views & @overall_views_clicks
      @more_info_and_clicks = @more_info_views & @overall_views_clicks
      @scrolled_and_cat_clicks = @scrolled_views & @counter_array
      @all = @overall_views_clicks & @scrolled_views & @more_info_views & @counter_array
    end
  end

  def dynamic_show
    # @selected_products = Video.find(params[:video_id]).products.where(product_category: params[:product_category])
    @selected_products = Product.where(product_category: params[:product_category])
    @view_id = params[:view_id]
    respond_to do |format|
      @selected_products
      @view_id
      format.js
    end
  end

  def register_category_click
    @view = View.find(params[:view_id])
    array = @view.category_clicks
    # new_cat = /All Products/.match(params[:category]) ? "All" : params[:category]
    array = array << params[:category]
    array = array.uniq
    @view.update(category_clicks: array)
    render json: "Success"
  end

  def record_session_duration
    @view = View.find(session[:user])
    @curr_sess_duration = @view.session_duration
    @sess_duration = ((DateTime.now - session[:time].to_datetime)*24*60*60).to_i + @curr_sess_duration
    @view.update(session_duration: @sess_duration)
    render json: "Success"
  end

  def update_session_time
    @view = View.find(session[:user])
    session[:time] = DateTime.now
    render json: "Success"
  end

  def active_media_duration
    @view = View.find(session[:user])
    @view.active_media_duration += params[:time].to_i
    @view.save

    head :ok
  end

  # def active_media_duration
  #   @view = View.find(session[:user])
  #   @curr_sess_duration = @view.active_media_duration
  #   @sess_duration = ((DateTime.now - session[:time].to_datetime)*24*60*60).to_i + @curr_sess_duration
  #   @view.update(active_media_duration: @sess_duration)

  #   head :ok
  # end

  def rv
    @video = Video.find(params[:id])
    # @products = @video.products
    if !session[:user]
      @view = View.create(video_id: @video.id, view_type: "rv")
      session[:user] = @view.id
      session[:time] = DateTime.now
    else
      @view = View.find(session[:user])
    end
    @all_other_video = Video.where.not(id: [params[:id]]).shuffle
    # @product_categories = @products.pluck(:product_category).uniq
    @related_videos = nil
    if params[:id] == '16' || params[:id] == '17'
      if params[:rv_id]
        @video = RelatedVideo.find(params[:rv_id])
        @related_videos = RelatedVideo.where(video_id: params[:id]).shuffle
      else
        @related_videos = RelatedVideo.where(video_id: params[:id])
      end
    else
      @related_videos = Video.where.not(id: [params[:id]]).shuffle
    end

    if params[:j]
      current_count = @view.jumps
      @view.update(jumps: current_count + 1)
    end
  end

  private

  def set_categories
    @categories = Video.all.pluck(:content_category).uniq
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_show.html.erb
<% selected_products.each do |product| %>
  <div>
    <%= link_to videos_click_product_path(view_id: view_id, product_id: product.id), method: 'post', target: "_blank" , class: "product-list-row" do %>
      <div class="product-thumbnail"><img class="product_picture" src="<%= product.picture %>"></div>
      <div class="product-details"><h3><%= product.title %></h3>
        <% if product.appeared_at != "0:00" && view_id == nil%>
          <h6>Appeared at: <%= product.appeared_at %></h6>
        <% end %>
      <h6 style="display: none;">RM <%= product.price %></h6></div>
    <% end %>
  </div>
<% end %>

<div style="display: flex; align-items: center; justify-content: center;">
  <button type="button" class="btn seemore-btn">See More Products</button>        
</div>

<%= javascript_tag do%>
  function clickedToast() {
    var strWindowFeatures = "location=yes,scrollbars=yes,status=yes";
    var URL = "https://www.google.com";
    var win = window.open(URL, "_blank", strWindowFeatures);
    $.ajax({
      type:'POST',
      url:'/track_toast_click',
      data: { view_id : $("#view_id").text() },
      success:function(){
        //I assume you want to do something on controller action execution success?
        console.log("success");
      }
    });
  }
  $( ".seemore-btn" ).on('click', function() {
    clickedToast();
  });
<% end %>

app/views/videos/_video.html.erb
<div class="video-wrapper">
<%= link_to video do %>
  <div class="video-block">
    <div class="video-thumbnail" style="background-image: url(<%= video.picture %>)">
      <h6><%= video.duration %></h6>
    </div>
    <div class="video-title">
      <%= video.title %>
    </div>
  </div>
<% end %>
</div>

app/views/videos/analytics.html.erb
<div class="col-md-12">
  <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading">Analytics on views</div>

    <!-- Table -->
    <table class="table  table-striped">
      <tr width="100%">
<!-- 1 --><th>Total Views</th>
<!-- 2 --><th>Scrolled</th>
<!-- 3 --><th>See More</th>
<!-- 4 --><th>Product Clicks</th>
<!-- 5 --><th>Cat. Clicks</th>
<!-- 5 --><th>Ori. Total</th>
<!-- 6 --><th>Total</th>
<!-- 7 --><th>Scrolled and See More</th>
<!-- 8 --><th>Scrolled and Product Clicked</th>
<!-- 9 --><th>Scrolled and Cat. Clicked</th>
<!--10 --><th>See More and Product Clicked</th>
<!--11 --><th>Did All</th>
      </tr>

      <tr class="table-striped">
<!-- 1 --><td><%= @total_views.count %></td>
<!-- 2 --><td><%= @scrolled_views.count %></td>
<!-- 3 --><td><%= @more_info_views.count %></td>
<!-- 4 --><td><%= @overall_views_clicks.count %></td>
<!-- 5 --><td><%= @counter_array.count %></td>
<!-- 5 --><td><%= @original_total.count %></td>
<!-- 6 --><td><%= @current_total.count %></td>
<!-- 7 --><td><%= @scrolled_and_more_info.count %></td>
<!-- 8 --><td><%= @scrolled_and_clicks.count %></td>
<!-- 9 --><td><%= @scrolled_and_cat_clicks.count %></td>
<!--10 --><td><%= @more_info_and_clicks.count %></td>
<!--11 --><td><%= @all.count %></td>
      </tr>
    </table>
  </div>
</div>

app/views/videos/archive_show.html.erb
<div class="programme-page">
  
<div class="youtube-player">
  <div class="video_player_container">
    <div class="signalling_container">
      <img src="http://www.clker.com/cliparts/1/H/k/P/S/l/dezzit-right-bt.svg" id="myImg">
      <%= image_tag("closebutton.png", id: "closeBtn") %>
      <% if @video.id == 16 %>
        <h4 id="signal_msg">Produk fesyen dan lebih lagi, dipakaikan oleh watak kegemaran anda!</h4>
      <% elsif @video.id == 17 %>
        <h4 id="signal_msg">最喜爱角色的时尚单品</h4>
      <% else %>
        <h4 id="signal_msg">Fashion products & merchandises worn & inspired by your favourite characters, & more!</h4>
      <% end %>
    </div>
    <span>

      <div class="plyrr">
        <div class="plyr" data-type="youtube" data-video-id="<%= @video.video_link %>"></div>      
        
      </div>  

    </span>
  </div>
  <div class="product-list-container egg-panel">
    <div style="width: 100%;">
      <div style="display: inline-block; float: left;">
        
        <h3 class="panel-title">Buy What You See</h3>
      </div>
      <div class="dropdown-products-list">
        <button class="dropbtn">All Products  &#x25BE</button>
        <div class="dropdown-content active-dropdown">
          <% @product_categories.each do |link| %>
            <%= link_to link, videos_dynamic_show_path(product_category: link, video_id: @video.id, view_id: @view.id), method: 'post', class: 'dropdown_links', remote: true %>
          <% end %>
        </div>
      </div>
      
    </div>
    <div class="product-list">

      <% @products.each do |product| %>
        <div>
          <%= link_to videos_click_product_path(view_id: @view.id, product_id: product.id), method: 'post', target: "_blank" , class: "product-list-row" do %>
            <div class="product-thumbnail"><img class="product_picture" src="<%= product.picture %>"></div>
            <div class="product-details"><h3><%= product.title %></h3>
              <% if product.appeared_at != "0:00" %>
                <h6>Appeared at: <%= product.appeared_at %></h6>
              <% end %>
            <h6 style="display: none;">RM <%= product.price %></h6></div>
          <% end %>
        </div>
      <% end %>

      <div style="display: flex; align-items: center; justify-content: center;">
        <button type="button" class="btn seemore-btn">See More Products</button>        
      </div>

    </div>
  </div>
</div>


  <div class="video-list-container">
    <h3 class="panel-title">More Videos</h3>
    <div class="video-list">

      <% @all_other_video.each do |video| %>
        <div>
          <%= link_to video_path(id: video.id, j: true), class: "video-list-row" do %>

            <div class="video-thumbnail"><img class="video_picture" src="<%= video.picture %>"><h6><%= video.duration %></h6></div>
            <div class="video-details"><h6><%= video.title %></h6></div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>


</div>

<span id="scroll_counter" style="color: white;">0</span>
<span id="view_id" style="color: white;"><%= @view.id %></span>

app/views/videos/dynamic_show.js.erb
$('.product-list').html("<%=escape_javascript render(partial: 'show', locals: {selected_products: @selected_products, view_id: @view_id}) %>");

app/views/videos/index.html.erb
<%= render 'layouts/navbar', categories: @categories, link: "/videos", digital: true %>

<div class="container" id="video-list">
  <%= render @videos %>
</div>
<div id="infinite-scrolling">
  <%= paginate @videos %>
</div>

<footer>
  <%= link_to("https://www.facebook.com/Find-It-111053949615332/") do %>
    <%= image_tag "fblogo.png" %>
  <% end %>
</footer>

app/views/videos/index.js.erb
$('#video-list').append('<%= j render @videos %>');
<% if @videos.next_page %>
  window.canScroll = true
  $('.pagination').replaceWith('<%= j paginate @videos %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/videos/rv.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="nav-header">

        <div class="logo" style="background-image: url(<%= asset_path 'finditlogo.png' %>)"></div>

    </div>
  </div>
</nav>


<div class="programme-page">
  
<div class="youtube-player">
  <div class="video_player_container">
    <div class="plyrr">

      <% if @video.video_link =~ /youtube/ %>
        <div class="plyr" data-type="youtube" data-video-id="<%= @video.video_link %>"></div>
      <% else %>
        <video controls>
          <source src="<%= @video.video_link %>" type="video/mp4">
        </video>
      <% end %>

      <div class="suggested-video-list-container egg-panel">
        <div style="width: 100%;">
          <div style="display: inline-block; float: left;">
            
            <h3 class="panel-title">Suggested Videos</h3>
          </div>
          
        </div>
        <div class="suggested-video-list">

          <% @related_videos.each do |video| %>
            <div>
              <%= link_to rv_path(id: video.try(:video_id) ? video.video_id : video.id, rv_id: video.try(:video_id) ? video.id : nil, j: true), class: "suggested-video-list-row" do %>
                <div class="suggested-video-thumbnail"><img class="suggested-video-list-picture" src="<%= video.picture %>"><h6><%= video.duration %></h6></div>
                <div class="suggested-video-details"><h3><%= video.title %></h3></div>
              <% end %>
            </div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>


  <div class="video-list-container">
    <h3 class="panel-title">More Videos</h3>
    <div class="video-list">

      <% @all_other_video.each do |video| %>
        <div>
          <%= link_to rv_path(id: video.id, rv_id: nil, j: true), class: "video-list-row" do %>

            <div class="video-thumbnail"><img class="video_picture" src="<%= video.picture %>"><h6><%= video.duration %></h6></div>
            <div class="video-details"><h6><%= video.title %></h6></div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>


</div>

<span id="scroll_counter" style="color: black;">0</span>
<span id="view_id" style="color: black;"><%= @view.id %></span>

app/views/videos/show.html.erb
<%= render 'layouts/navbar', categories: @categories, link: "/videos", digital: true %>

<div class="programme-page">

<div class="youtube-player">
  <div class="video_player_container">
    <div class="plyrr">
      <% if @video.video_link =~ /youtube/ %>
        <div class="plyr" data-type="youtube" data-video-id="<%= @video.video_link %>"></div>
      <% else %>
        <video controls>
          <source src="<%= @video.video_link %>" type="video/mp4">
        </video>
      <% end %>
      <div class="product-list-container egg-panel">
        <div class="tooltip"></div>
        <div id="on-screen-product"></div>
        <div class="product-list">
          <% @products.each do |product| %>
          <div>
            <div class="product-list-row" data-appear-at="<%= product.appeared_at_in_sec %>" data-product-id="<%= product.id %>">
              <div class="product-thumbnail">
                <div class="product_picture" style="background-image: url(<%= product.picture %>)"></div>
              </div>
              <div class="product-details">
                <p class="on-screen">On Screen:</p>
                <h3><%= product.title %></h3>
                <% if product.appeared_at != "0:00" %>
                  <div class="exact-container">
                    <h6>Appeared at:
                      <%= product.appeared_at %>
                    </h6>
                    <% if product.match_type == 'Exact' %>
                      <div class="exact-word-wrapper"><h6>Exact</h6></div>
                    <% end %>
                  </div>
                <% end %>
                <h6 style="display: none;">RM
                  <%= product.price %>
                </h6>
              </div>
            </div>

          </div>
          <% end %>

          <div style="display: flex; align-items: center; justify-content: center;">
            <button type="button" class="btn seemore-btn">See More Products</button>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>


<div class="video-list-container">
  <h3 class="similar-video-title">Similar TV Shows</h3>
  <div class="video-list">
    <% @all_other_video.each do |video| %>
      <%= link_to video_path(id: video.id, j: true) do %>
        <div class="video-list-row">
          <div class="video-thumbnail">
            <div class="video_picture" style="background-image: url(<%= video.picture %>)"></div>
            <!-- <img class="video_picture" src="<%= video.picture %>"> -->
            <h6><%= video.duration %></h6>
          </div>
          <div class="video-details">
            <h6><%= video.title %></h6>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>


</div>
<%= render "products/modal" %>
<span id="scroll_counter" style="color: black;">0</span>
<span id="view_id" style="color: black;"><%= @view.id %></span>

app/views/videos/show_manual.html.erb
<div class="programme-page">
  
<div class="youtube-player">
  <div class="video_player_container">
    <div class="signalling_container">
      <img src="http://www.clker.com/cliparts/1/H/k/P/S/l/dezzit-right-bt.svg" id="myImg">
      <%= image_tag("closebutton.png", id: "closeBtn") %>
      <h4 id="signal_msg">Fashion products & merchandises worn & inspired by your favourite characters, & more!</h4>
    </div>
    <span>
      <div class="plyrr">
        <div class="plyr" data-type="youtube" data-video-id="<%= @video.video_link %>"></div>      
      </div>     

    </span>
  </div>
  <div class="product-list-container egg-panel">
    <div style="width: 100%;">
      <div style="display: inline-block; float: left;">
        
        <h3 class="panel-title">Buy What You See</h3>
      </div>
      <div class="dropdown-products-list">
        <button class="dropbtn">All Products  &#x25BE</button>
        <div class="dropdown-content active-dropdown">
          <% @product_categories.each do |link| %>
            <%= link_to link, videos_dynamic_show_path(product_category: link, video_id: @video.id, view_id: nil), method: 'post', class: 'dropdown_links', remote: true %>
          <% end %>
        </div>
      </div>
      
    </div>
    <div class="product-list">

      <% @products.each do |product| %>
        <div>
          <%= link_to videos_click_product_path(view_id: nil, product_id: product.id), method: 'post', target: "_blank" , class: "product-list-row" do %>
            <div class="product-thumbnail"><img class="product_picture" src="<%= product.picture %>"></div>
            <div class="product-details"><h3><%= product.title %></h3>
              <% if product.appeared_at != "0:00" %>
                <h6>Appeared at: <%= product.appeared_at %></h6>
              <% end %>
            <h6 style="display: none;">RM <%= product.price %></h6></div>
          <% end %>
        </div>
      <% end %>

      <div style="display: flex; align-items: center; justify-content: center;">
        <button type="button" class="btn seemore-btn">See More Products</button>        
      </div>

    </div>
  </div>
</div>


  <div class="video-list-container">
    <h3 class="panel-title">More Videos</h3>
    <div class="video-list">

      <% @all_other_video.each do |video| %>
        <div>
          <%= link_to show_manual_path(video.id), class: "video-list-row" do %>

            <div class="video-thumbnail"><img class="video_picture" src="<%= video.picture %>"><h6><%= video.duration %></h6></div>
            <div class="video-details"><h6><%= video.title %></h6></div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>


</div>

<span id="scroll_counter" style="color: white;">0</span>
<span id="view_id" style="color: white;"></span>

app/views/videos/woc.html.erb
<div class="programme-page">
  
<div class="youtube-player" style="padding-bottom: 20px">
  <div class="video_player_container">
    <div class="signalling_container">
      <img src="http://www.clker.com/cliparts/1/H/k/P/S/l/dezzit-right-bt.svg" id="myImg">
      <%= image_tag("closebutton.png", id: "closeBtn") %>
      <h4 id="signal_msg">Fashion products & merchandises worn & inspired by your favourite characters, & more!</h4>
    </div>
    <span>

      <div class="plyrr">
        <div class="plyr" data-type="youtube" data-video-id="<%= @video.video_link %>"></div>      
      </div>


    </span>
  </div>
</div>


<div class="video-list-container">
  <h3 class="panel-title">More Videos</h3>
  <div class="video-list">

    <% @all_other_video.each do |video| %>
      <div>
          <%= link_to woc_path(id: video.id, j: true), class: "video-list-row" do %>

          <div class="video-thumbnail"><img class="video_picture" src="<%= video.picture %>"><h6><%= video.duration %></h6></div>
          <div class="video-details"><h6><%= video.title %></h6></div>
        <% end %>
      </div>
    <% end %>

  </div>
</div>


</div>

<span id="scroll_counter" style="color: white;">0</span>
<span id="view_id" style="color: white;"><%= @view.id %></span>
<span id="woc" style="color: white;"></span>