config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:show] do
    member do
      get :exact_match
      post :toggle_product
    end
  end
  resources :exact_requests, only: [:show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "videos#index"
  resources :videos
  post "/click_product" => "videos#click_product"

  post '/track_scroll' => "videos#track_scroll"
  post '/register_category_click' => "videos#register_category_click"
  post '/record_session_duration' => "videos#record_session_duration"
  post '/update_session_time' => "videos#update_session_time"
  post '/track_toast_click' => "videos#track_toast_click"
  post '/active_media_duration' => "videos#active_media_duration"
  get 'videosm/:id' => "videos#show_manual", as: "show_manual"
  get 'videos/woc/:id' => "videos#woc", as: "woc"
  get '/analytics/:id' => "videos#analytics"
  post 'videos/dynamic_show' => 'videos#dynamic_show'
  get 'videos/rv/:id' => "videos#rv", as: "rv"

  # FOR LINEAR LANDING
  resources :scenes
  get '/t&c' => "scenes#t_and_c", as: "t_and_c"
end

app/models/exact_request.rb
class ExactRequest < ApplicationRecord
  belongs_to :view
  belongs_to :product
  validates_uniqueness_of :email, scope: [:view_id, :product_id]
end

app/controllers/exact_requests_controller.rb
class ExactRequestsController < ApplicationController
  def create
    @exact_request = ExactRequest.new(exact_request_params.merge(view_id: session[:user]))

    if @exact_request.save
      @message = "Request created successfully"
    else
      @product = Product.find(exact_request_params[:product_id])
      
      render "products/exact_match"
    end
  end

  private

  def exact_request_params
    params.require(:exact_request).permit(:email, :product_id)
  end
end

app/helpers/exact_requests_helper.rb
module ExactRequestsHelper
end

app/views/exact_requests/_form.html.erb
<h4>
  <p>Want an exact match of <span style="color: #C12A68"><%= product.title %></span>?</p>
  <p>Drop your email and we will get it for you and contact you afterwards!</p>
</h4>
<%= form_for :exact_request, url: exact_requests_path(exact_request), remote: true do |f| %>

  <%= render "shared/error_messages", target: exact_request %>

  <div class="form-group">
    <%= f.email_field :email, class: "form-control", id: "inputEmail", placeholder: "Enter your email..." %>
  </div>
  <%= f.hidden_field :product_id, value: product.id %>
  <button type="submit" class="btn">Submit</button>
<% end %>

app/views/exact_requests/create.js.erb
$("#exactMatch").modal("hide");
toastr.success("<%= @message %>")