config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:show] do
    member do
      get :exact_match
      post :toggle_product
    end
  end
  resources :exact_requests, only: [:show, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "videos#index"
  resources :videos
  post "/click_product" => "videos#click_product"

  post '/track_scroll' => "videos#track_scroll"
  post '/register_category_click' => "videos#register_category_click"
  post '/record_session_duration' => "videos#record_session_duration"
  post '/update_session_time' => "videos#update_session_time"
  post '/track_toast_click' => "videos#track_toast_click"
  post '/active_media_duration' => "videos#active_media_duration"
  get 'videosm/:id' => "videos#show_manual", as: "show_manual"
  get 'videos/woc/:id' => "videos#woc", as: "woc"
  get '/analytics/:id' => "videos#analytics"
  post 'videos/dynamic_show' => 'videos#dynamic_show'
  get 'videos/rv/:id' => "videos#rv", as: "rv"

  # FOR LINEAR LANDING
  resources :scenes
  get '/t&c' => "scenes#t_and_c", as: "t_and_c"
end

app/views/layouts/_dropdown.html.erb
<ul class="nav">
  <li class="dropdown">
    <a class="dropdown-toggle category" data-toggle="dropdown" href="#">Category
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu category-dropdown">
      <% categories.each do |category| %>
      <li>
        <%= link_to category, videos_path(category: category) %>
      </li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/layouts/_filter.html.erb
<ul class="nav" style="text-align: center;">
  <li class="dropdown">
    <a class="dropdown-toggle category" data-toggle="dropdown" href="#">Sort By
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu category-dropdown category-dropdown-scenes">
      <li class="dropdown-submenu">
        <%= link_to "Products", "#", class: "submenu-opener" %>
        <ul class="dropdown-menu">
          <li>
          <%= link_to "Red Velvet Ep.13", scenes_path(filter: true, type: "products", episode: 1) %>
          </li>
          <li>
          <%= link_to "Red Velvet Ep.14", scenes_path(filter: true, type: "products", episode: 2) %>            
          </li>
        </ul>
      </li>

      <li class="dropdown-submenu">
        <%= link_to "Scenes", "#", class: "submenu-opener" %>
        <ul class="dropdown-menu">
          <li>
          <%= link_to "Red Velvet Ep.13", scenes_path(filter: true, type: "scenes", episode: 1) %>
          </li>
          <li>
          <%= link_to "Red Velvet Ep.14", scenes_path(filter: true, type: "scenes", episode: 2) %>            
          </li>
        </ul>
      </li>

    </ul>
  </li>

  <li class="dropdown">
    <%= link_to "T&C", t_and_c_path, class: "dropdown-toggle category" %>
  </li>
</ul>

app/views/layouts/_footer.html.erb
<% if Rails.env == "production" %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-105306512-1', 'auto');
    ga('send', 'pageview');

    if (typeof gon.event_tracker !== "undefined") {
      ga('send', 'event', gon.event_tracker.category, gon.event_tracker.action, gon.event_tracker.label);
    }

  </script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <div class="nav-header">
      <%= link_to(link) do %>
        <div class="logo" style="background-image: url(<%= asset_path 'finditlogo.png' %>)"></div>
      <% end %>
    </div>
    <% if digital %>
      <%= render 'layouts/dropdown', categories: categories %>
    <% else %>
      <%= render 'layouts/filter' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindIt</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta property="og:title"              content="FindIt" />
    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '771833002989285');
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=771833002989285&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->

  </head>

  <body>
    <%= Gon::Base.render_data({}) %>

    <%= yield %>
    
    <%= render "layouts/footer" %>


  </body>
</html>